def feedback():
    print("ENQUIRY FORM")
    print()
    name=input("Enter name of customer:")
    mobile=eval(input("Enter mobile no:"))
    telephone=eval(input("Enter alternate telephone no:"))
    email=input("Enter email-id:")
    print()
    print()
    print("Is this a corporate or an individual enquiry:")
    print("i.Corporte")
    print("ii.Individual")
    choice1=input("Enter your choice:")
    print()
    print()
    print("How did you hear about us:")
    print("1.None")
    print("2.Website/Google")
    print("3.Referral from Customer")
    print("4.Returning Customer")
    print("5.Entertainer")
    print("6.Facebook")
    print("7.Referral from agent")
    print("8.Brochure/flyer")
    print("9.Corporate offer for employees")
    print("10.Email")
    print("11.Car/Van on the road")
    print("12.Other")
    choice2=eval(input("Enter your choice:"))
    print()
    print()
    print()
    message=input("Please enter your enquiry,if any:")
    print()
    message=input("How was your experience?What went wrong?(required)")
    print()
    print()
    print("Will you be returning to Car Rent?")
    print("a.Yes")
    print("b.No")
    choice2=input("Enter your choice:")
